name: coin_rank
description: project to demonstrate the MVVM design pattern using getX state management.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: any
  get: any


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
